name: Check File Changes

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  check-files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script
        run: python .github/workflows/check_changed_files.py "${{ github.base_ref }}" "${{ github.sha }}"
