name: Check File Changes

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  check-files:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pydocstyle

      - name: Run Python script
        run: |
          python .github/workflows/check_changed_files.py "${{ github.base_ref }}" "${{ github.head_ref }}"

      - name: Run Black
        run: black --check .

      - name: Run Pydocstyle
        run: pydocstyle .
