name: Limit File Changes

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  limit-file-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Count Changed Files
        id: count-files
        run: echo "::set-output name=changed_files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | wc -l)"

      - name: Check File Changes Limit
        run: |
          changedFiles=${{ steps.count-files.outputs.changed_files }}
          if [ $changedFiles -gt 20 ]; then
            echo "Error: Too many file changes ($changedFiles). Maximum allowed is 20."
            exit 1
          else
            echo "File changes within limit ($changedFiles)."
          fi
