##############################################################################
##############################################################################
#
# NOTE!
#
# Please read the README.md file in this directory that defines what should
# be placed in this file
#
##############################################################################
##############################################################################

name: PR Workflow

on:
  pull_request:
    branches:
      - '**'

jobs:
  
  Check-Changed-Files:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Run Python script
        run: |
          python .github/workflows/count_changed_files.py --file_count --base_branch "${{ github.base_ref }}" --PR_branch "${{ github.head_ref }}"

