name: Check File Changes

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  count-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Count changed files
        id: count-files
        run: |
          file_count=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | wc -l)
          echo "File count: $file_count"
          echo "::set-output name=file_count::$file_count"

      - name: Check file count
        run: |
          if [ ${{ steps.count-files.outputs.file_count }} -gt 20 ]; then
            echo "Error: Too many files (greater than 20) changed in the pull request."
            echo "Possible issues:"
            echo "- Contributor may be merging into an incorrect branch."
            echo "- Source branch may be incorrect."
            exit 1
          fi
